Update copyright, fix config location, fix exits, fix SBDIR

diff --git a/faac.SlackBuild b/faac.SlackBuild
--- a/faac.SlackBuild
+++ b/faac.SlackBuild
@@ -1,15 +1,31 @@
 #!/bin/sh
 #
-# SlackBuild for FAAC
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for FAAC
+# Copyright (C) 2007-2016 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+# 
+# $Id: faac.SlackBuild,v 1.4.4.1 2016/08/18 18:04:17 gsotirov Exp $
 #
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=faac
 VERSION=1.28
-BUILD=2
 ARCH=${ARCH:-i486}
+BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
@@ -34,12 +50,13 @@ mkdir -p $PKG
 
 # Extract and fix source
 cd $TMP
-tar xvf $CWD/$NAME-$VERSION.tar.bz2
+tar -xvf $CWD/$NAME-$VERSION.tar.?z* || exit 3
 cd $NAME-$VERSION
 fix_source
 
 # Apply patches
-patch -p1 < $CWD/$NAME-$VERSION-with_mp4.diff
+patch -p1 < $CWD/$NAME-$VERSION-with_mp4.diff || exit 4
+patch -p1 < $CWD/$NAME-$VERSION-build.diff || exit 4
 
 # Configure
 CFLAGS=$SLKCFLAGS \
@@ -47,18 +64,15 @@ CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --host=$ARCH-slackware-linux \
             --prefix=/usr \
+            --libdir=/usr/lib${LIBDIRSUFFIX} \
             --mandir=/usr/man \
             --enable-shared=yes \
             --enable-static=no \
-            --with-mp4v2 || exit 2
+            --with-mp4v2 || exit 5
 
 # Build & install
-make -j4 all || exit 3
-
-PKG="$TMP/package-$NAME"
-mkdir -p $PKG
-
-make DESTDIR=$PKG install || exit 4
+make -j4 all || exit 6
+make DESTDIR=$PKG install || exit 7
 
 # Prepare
 bin_perms $PKG
@@ -70,13 +84,15 @@ mkdir -p $PKG/install
 install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
 install -m 644 $CWD/slack-required $PKG/install/slack-required
 
-mkdir -p $PKG/usr/src/slackbuilds/$NAME-$VERSION
-install -m 644 $CWD/$NAME-$VERSION-with_mp4.diff \
-               $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME-$VERSION-with_mp4.diff
-install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-desc
-install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
-install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
+SBDIR=$PKG/usr/src/slackbuilds/$NAME-$VERSION
+mkdir -p $SBDIR
+install -m 644 $CWD/$NAME-$VERSION-with_mp4.diff   $SBDIR/$NAME-$VERSION-with_mp4.diff
+install -m 644 $CWD/$NAME-$VERSION-build.diff $SBDIR/$NAME-$VERSION-build.diff
+install -m 644 $CWD/slack-desc                     $SBDIR/slack-desc
+install -m 644 $CWD/slack-required                 $SBDIR/slack-required
+install -m 644 $CWD/$NAME.SlackBuild               $SBDIR/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -84,6 +100,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up (optional)
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
